apiVersion: v1
kind: Pod
metadata:
  name: dan-tests
spec:
  restartPolicy: OnFailure
  containers:
  - name: cuda-vectoradd
    image: "nvidia/samples:vectoradd-cuda11.2.1"
    resources:
      requests:
        memory: "32Gi"
        nvidia.com/gpu: 1
      limits:
	memory: "32Gi"
        nvidia.com/gpu: 1
    command:
    - /bin/bash
    - -c
    - |
      PATH="/root/miniconda3/bin:${PATH}"
      apt-get update
      apt-get install -y python3.8
      apt-get install -y wget
      wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
      mkdir /root/.conda
      bash Miniconda3-latest-Linux-x86_64.sh -b
      conda init
      conda create -y -n torchEnv python=3.11
      source activate torchEnv
      conda install -y pytorch torchvision torchaudio pytorch-cuda=12.1 -c pytorch -c nvidia
      apt-get install -y git
      git clone https://www.github.com/DanRunfola/kubeTests
      cd kubeTests
      python gpu.py
      sleep 99999
